configuration:
  dependencies:
  - mvn://com.walmartlabs.concord.plugins:jenkins-task:1.40.0

flows:
  default:
  - task: jenkins
    in:
      baseUrl: "http://20.235.5.90:8080"
      username: "JenkinsAdmin"
      apiToken: "11f67de0970a82d4064421a3158e3fce8c"
      jobName: "ASA-CICD"

triggers:
# fire when concord.yml is modified
- github:
    entryPoint: "onConcordUpdate"
    conditions:
      type: "push"
      branch: "master"
      files:
        modified:
          - "concord.yml"

# fire when any file within src/ is added, modified, or deleted
- github:
    entryPoint: "onSrcChanged"
    conditions:
      type: "push"
      branch: "master"
      files:
        any:
          - "src/.*"


