configuration:
  dependencies:
  - mvn://com.walmartlabs.concord.plugins:jenkins-task:1.40.0

flows:
  default:
  - task: jenkins
    in:
      baseUrl: "http://20.235.5.90:8080"
      username: "JenkinsAdmin"
      apiToken: "11f67de0970a82d4064421a3158e3fce8c"
      jobName: "ASA-CICD"

triggers:
- github:
    useInitiator: true
    entryPoint: onPush
    conditions:
      type: push

